### ISSUE TITLE
image not found?

### ISSUE THREAD

**Issue by sallest** [olzzon/tv2-inews-ftp-gateway#18]
I Tried docker up with inews-ftp but got that mensage below, do you know what that means?

**info@sofiebau:~/sofie$ sudo docker-compose up**
[sudo] password for info:
Pulling inews-gateway (olzzon/tv2-inews-ftp-gateway:master)...
ERROR: manifest for olzzon/tv2-inews-ftp-gateway:master not found: manifest unknown: manifest unknown
info@sofiebau:~/sofie$

**info@sofiebau:~/sofie$ vi docker-compose.yaml**
-- This is NOT recommended to be used for a production deployment. It aims to quickly get an evaluation version of sofie running and serve as a basis for how to setup a production deployment
version: "3.3"
services:

  db:
    hostname: mongo
    image: mongo:4.2.8
    restart: always

    ports:
      - "3001:27017" # Expose mongo on the same port as dev meteor does
    volumes:
      - db-data:/data/db
    networks:
      - sofie

  core:
    hostname: core
    image: sofietv/tv-automation-server-core:master
    restart: always
    ports:
      - "3000:3000" # Same port as meteor uses by default
    environment:
      PORT: "3000"
      MONGO_URL: "mongodb://db:27017/meteor"
      ROOT_URL: "http://localhost:3000"
    networks:
      - sofie
    volumes:
      - snapshots:/mnt/snapshots
    depends_on:
      - db

  playout-gateway:
    image: sofietv/tv-automation-playout-gateway:master
    restart: always
    command: yarn start -host core -port 3000
    networks:
      - sofie
    depends_on:
      - core

  inews-gateway:
     image: olzzon/tv2-inews-ftp-gateway:master
     restart: always
     command: yarn start -host core -port 3000
     networks:
       - sofie
     depends_on:
       - core

networks:
  sofie:

volumes:
  db-data:
  snapshots:

**Comment by sallest** [comment]
Change 'master' to 'develop', and run..
"image: olzzon/tv2-inews-ftp-gateway:master"

Now, when run show mensagem below:


inews-gateway_1    | yarn run v1.22.5
inews-gateway_1    | $ node dist/index.js -host core -port 3000
inews-gateway_1    | Logging to Console
inews-gateway_1    | {"level":"info","message":"-----------------------------------"}
inews-gateway_1    | {"level":"info","message":"Statup options:"}
inews-gateway_1    | {"level":"info","message":"host: \"127.0.0.1\""}
inews-gateway_1    | {"level":"info","message":"port: 3000"}
inews-gateway_1    | {"level":"info","message":"log: \"\""}
inews-gateway_1    | {"level":"info","message":"id: \"\""}
inews-gateway_1    | {"level":"info","message":"token: \"\""}
inews-gateway_1    | {"level":"info","message":"debug: false"}
inews-gateway_1    | {"level":"info","message":"certificates: []"}
inews-gateway_1    | {"level":"info","message":"disableWatchdog: false"}
inews-gateway_1    | {"level":"info","message":"unsafeSSL: false"}
inews-gateway_1    | {"level":"info","message":"-----------------------------------"}
inews-gateway_1    | {"level":"info","message":"Core: 127.0.0.1:3000"}
inews-gateway_1    | {"level":"info","message":"-----------------------------------"}
inews-gateway_1    | {"level":"info","message":"Initializing Process..."}
inews-gateway_1    | {"level":"info","message":"Process initialized"}
inews-gateway_1    | {"level":"info","message":"Initializing Core..."}
inews-gateway_1    | {"level":"error","message":"Core Error: ddpError: Network error: ws://127.0.0.1:3000/websocket: connect ECONNREFUSED 127.0.0.1:3000"}
inews-gateway_1    | {"level":"error","message":"Error during initialization: Network error: ws://127.0.0.1:3000/websocket: connect ECONNREFUSED 127.0.0.1:3000"}
inews-gateway_1    | {"level":"info","message":"Shutting down in 10 seconds!"}



Need config inews to receive connection from ftp? have one step by step where can i do the config in inews?

**Comment by olzzon** [comment]
You add the inews gateway in Sofie, and do the config from there.

**Comment by sallest** [comment]
Hello olzzon

Where can I add inews gw in Sofie? 

Status page:
![image](https://user-images.githubusercontent.com/80831913/112151104-9af9ab00-8bbf-11eb-9b22-ec824f29b209.png)

Settings page:
![image](https://user-images.githubusercontent.com/80831913/112151139-a8169a00-8bbf-11eb-878a-77fcbd7e9b10.png)


I Don't found

**Comment by olzzon** [comment]
The full Sofie docs are here: https://github.com/nrkno/Sofie-TV-automation
And then i recommend you to join Sofie slack channel: sofietv.slack.com

**Comment by sallest** [comment]
I Don't saw in the doc details about the inews gateway.

Could you send a invite to domain @tvtem.com, I cant go into the channel.

thiago.salles@tvtem.com

**Comment by sallest** [comment]
Thanks you!
